config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "dashboards", to: "dashboards#show"
  
  get 'sessions/new'

  get 'usuarios/new'
    
  get 'objetivos', to: 'objetivos#new'
  get 'objetivos/:id/edit', to: 'objetivos#edit', as: 'edit_objetivo'
  resources :objetivos

  get 'dividas', to: 'dividas#new'
  resources :dividas

  get 'rendas', to: 'rendas#new'
  resources :rendas

  get 'recursos', to: 'recursos#new'
  resources :recursos

  get 'usuario_info', to: 'usuario_info#new'
  get 'usuario_info/:id/edit', to: 'usuario_info#edit', as: 'edit_usuario_info'
  resources :usuario_info

  resources :usuarios
  get 'sign_in' => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  root 'sessions#new'

end

app/models/usuario_info.rb
class UsuarioInfo < ApplicationRecord
    validates :foto, presence: { message: "É obrigatório informar a profissão!" }, length: {maximum: 500, message: "Deve ter no máximo 500 caracteres"}
    validates :idade, presence: { message: "É obrigatório informar a profissão!" }, length: {maximum: 3, message: "Deve ter no máximo 3 dígitos"}, format: { :with => /\A(?=.*[1-9])\d*(?:(\.|,)\d{1,2})?\z/, message: "Formato de idade inválida!" }
    validates :genero, presence: { message: "É obrigatório informar a profissão!" }, length: {maximum: 20, message: "Deve ter no máximo 20 caracteres"}
    validates :telefone, presence: { message: "É obrigatório informar a profissão!" }, length: {maximum: 50, message: "Deve ter no máximo 50 caracteres"}
end

app/controllers/usuario_info_controller.rb
class UsuarioInfoController < ApplicationController
    before_action :authorize

    def new
        @usuario_info = UsuarioInfo.new
    end

    def create
        @usuario_info = UsuarioInfo.new(usuario_info_params) 
        @usuario_info.user_id = current_usuario.id
        if @usuario_info.save
            redirect_to dashboards_path
        else
            render :new, status: :unprocessable_entity, content_type: "text/html"
            headers["Content-Type"] = "text/html"
        end            
    end

    def show
        @usuario_info = UsuarioInfo.find(params[:id])
    end

    def edit
        @usuario_info = UsuarioInfo.find(params[:id])
    end

    def update
        @usuario_info = UsuarioInfo.find(params[:id])
        if @usuario_info.update(usuario_info_params)
            flash[:success] = "Informações adicionais atualizada"
            redirect_to dashboards_path
        else
            render 'edit'
        end
    end

    public
    def usuario_info_params
        params.require(:usuario_info).permit(:foto, :idade, :genero, :telefone)
    end
end

app/helpers/usuario_info_helper.rb
module UsuarioInfoHelper
end

app/views/usuario_info/new.html.erb
<section class='main-content'>

  <div class='form-titulo'>Personalizar perfil</div>

  <div class='white-box'>
    <% if @usuario_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario_info.errors.count, "erro") %> impedem que a conta/divida seja gravada no banco de dados:</h2>

      <ul>
      <% @usuario_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with scope: :usuario_info, url: usuario_info_path, local: true do |form| %>

      <p class='form-label'><%= form.label :foto, 'Foto URL:' %></p>
      <p class='form-input'><%= form.text_field :foto %></p>

      <p class='form-label'><%= form.label :idade, 'Idade:' %></p>
      <p class='form-input'><%= form.text_field :idade %></p>

      <p class='form-label'><%= form.label :genero, 'Gênero:' %></p>
      <p class='form-input'><%= form.text_field :genero %></p>

      <p class='form-label'><%= form.label :telefone, 'Telefone:' %></p>
      <p class='form-input'><%= form.text_field :telefone %></p>

      <p class='form-btn'><%= form.submit 'Cadastrar' %></p>
    <% end %>
  </div>

</section>

app/views/usuario_info/show.html.erb
<p>
  <strong>Foto:</strong>
  <%= @usuario_info.foto %>
</p>
 
<p>
  <strong>Idade:</strong>
  <%= @usuario_info.idade %>
</p>

<p>
  <strong>Gênero:</strong>
  <%= @usuario_info.genero %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @usuario_info.telefone %>
</p>