config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "dashboards", to: "dashboards#show"
  
  get 'sessions/new'

  get 'usuarios/new'
    
  get 'objetivos', to: 'objetivos#new'
  get 'objetivos/:id/edit', to: 'objetivos#edit', as: 'edit_objetivo'
  resources :objetivos

  get 'dividas', to: 'dividas#new'
  resources :dividas

  get 'rendas', to: 'rendas#new'
  resources :rendas

  get 'recursos', to: 'recursos#new'
  resources :recursos

  get 'usuario_info', to: 'usuario_info#new'
  get 'usuario_info/:id/edit', to: 'usuario_info#edit', as: 'edit_usuario_info'
  resources :usuario_info

  resources :usuarios
  get 'sign_in' => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  root 'sessions#new'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

    before_action :authorize

    def show
        @rendas = Renda.where(user_id: current_usuario.id)
        @dividas = Divida.where(user_id: current_usuario.id)
        @objetivos = Objetivo.where(user_id: current_usuario.id)
        @recursos = Recurso.where(user_id: current_usuario.id)
    end

end

app/views/dashboards/show.html.erb
<% if logged_in? %>

	<section class='main-content'>

		<div class='white-box'>
			<h1>Seja bem vindo ao seu dashboard, <%= @current_usuario.nome%>!</h1>
		</div>

		<div class='green-box'>
			<h2>Cadastre sua renda mensal</h2>
			<button class='green-box-btn'><strong><%= link_to "Cadastrar Renda", rendas_path%></strong></button>	
		</div>
		
		<div class='white-box'>
			<table id='tabela' class='itens-tabela'>
				<tr>
					<th>Profissão</th>
					<th>Empresa</th>
					<th>Salário</th>
					<th>Editar</th>
					<th>Deletar</th>
				</tr>

				<% Array(@rendas).each do |renda| %>
				<tr class='conteudo-tabela-renda'>
					<td id='Profissao'><%= renda.profissao %></td>
					<td><%= renda.empresa %></td>
					<td>R$ <%= renda.salario %></td>
					<td><%= link_to "Editar", edit_renda_path(renda) %></td>
					<td><%= button_to "Delete", {:controller => :rendas,
		:action => 'destroy', :id => renda.id }, :method => :delete %></td>
				</tr>
				<% end %>
			</table>
		</div>


		
		<div class='green-box'>
			<h2> Cadastre uma dívida qualquer </h2>
			<button class='green-box-btn'><strong><%= link_to "Cadastrar Dívida", dividas_path%></strong></button>
		</div>

		<div class='white-box'> 
			<table id='tabela' class='itens-tabela'>
				<tr>
					<th>Nome</th>
					<th>Descrição</th>
					<th>Periodo</th>
					<th>Valor</th>
					<th>Editar</th>
					<th>Deletar</th>
				</tr>
			
				<% Array(@dividas).each do |divida| %>
				<tr class='conteudo-tabela-divida'>
					<td><%= divida.nome %></td>
					<td><%= divida.descricao %></td>
					<td><%= divida.periodo %></td>
					<td>R$ <%= divida.valor %>,00</td>
					<td><%= link_to "Editar", edit_divida_path(divida) %></td>
					<td><%= button_to "Delete", {:controller => :dividas,
	:action => 'destroy', :id => divida.id }, :method => :delete %></td>
				</tr>
				<% end %>
			</table>
		</div>




		<div class='green-box'>
			<h2> Cadastre um objetivo a ser atingido </h2>
			<button class='green-box-btn'><strong><%= link_to "Cadastrar Objetivo", objetivos_path%></strong></button>
		</div>

		<div class='white-box'>
			<table id='tabela' class='itens-tabela'> 
				<tr> 
					<th>Titulo</th>
					<th>Descrição</th>
					<th>Editar</th>
					<th>Deletar</th>
				</tr>
			

				<% Array(@objetivos).each do |objetivo| %>
				<tr class='conteudo-tabela-objetivo'>
					<td><%= objetivo.titulo %></td>
					<td><%= objetivo.descricao %></td>
					<td><%= link_to "Editar", edit_objetivo_path(objetivo) %></td>
					<td><%= button_to "Delete", {:controller => :objetivos,
	:action => 'destroy', :id => objetivo.id }, :method => :delete %></td>
				</tr>
				<% end %>

			</table>
		</div>



		<div class='green-box'>
			<h2> Cadastre um recurso extraordinário qualquer </h2>
			<button class='green-box-btn'><strong><%= link_to "Cadastrar Recurso Extraodinário", recursos_path%></strong></button>
		</div>

		<div class='white-box'> 
			<table id='tabela' class='itens-tabela'>
				<tr>
					<th>Nome</th>
					<th>Valor</th>
					<th>Editar</th>
					<th>Deletar</th>
				</tr>
			
				<% Array(@recursos).each do |recurso| %>
				<tr class='conteudo-tabela-recurso'>
					<td><%= recurso.nome %></td>
					<td>R$ <%= recurso.valor %>,00</td>
					<td><%= link_to "Editar", edit_recurso_path(recurso) %></td>
					<td><%= button_to "Delete", {:controller => :recursos,
	:action => 'destroy', :id => recurso.id }, :method => :delete %></td>
				</tr>
				<% end %>
			</table>
		</div>

	</section>
<% else %>
    <li><%= link_to "Log in", root_path %></li>
<% end %>