config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "dashboards", to: "dashboards#show"
  
  get 'sessions/new'

  get 'usuarios/new'
    
  get 'objetivos', to: 'objetivos#new'
  get 'objetivos/:id/edit', to: 'objetivos#edit', as: 'edit_objetivo'
  resources :objetivos

  get 'dividas', to: 'dividas#new'
  resources :dividas

  get 'rendas', to: 'rendas#new'
  resources :rendas

  get 'recursos', to: 'recursos#new'
  resources :recursos

  get 'usuario_info', to: 'usuario_info#new'
  get 'usuario_info/:id/edit', to: 'usuario_info#edit', as: 'edit_usuario_info'
  resources :usuario_info

  resources :usuarios
  get 'sign_in' => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  root 'sessions#new'

end

app/models/objetivo.rb
class Objetivo < ApplicationRecord
    validates :titulo, presence: { message: "É obrigatório informar um nome." }
    validates :descricao, presence: { message: "É obrigatório informar um periodo de cobrança." }
end

app/controllers/objetivo_controller.rb
class ObjetivoController < ApplicationController
    def new
        @objetivo = Objetivo.new
    end
    def create
        @objetivo = Objetivo.new(objetivo_params)
        if @objetivo.save
            redirect_to "/usuarios/1"
        else
            render :new, status: :unprocessable_entity, content_type: "text/html"
            headers["Content-Type"] = "text/html"
        end
    end
    def show
        @objetivo = Objetivo.find(params[:id])
    end
    private
    def objetivo_params
        params.require(:objetivo).permit(:titulo, :descricao)
    end
end

app/controllers/objetivos_controller.rb
class ObjetivosController < ApplicationController
    before_action :authorize
    def new
        @objetivo = Objetivo.new
    end

    def destroy
        @objetivo = Objetivo.find(params[:id])
        @objetivo.destroy
      
        redirect_to dashboards_path
    end

    def create
        @objetivo = Objetivo.new(objetivo_params)
        @objetivo.user_id = current_usuario.id
        if @objetivo.save
            redirect_to dashboards_path
        else
            render :new, status: :unprocessable_entity, content_type: "text/html"
            headers["Content-Type"] = "text/html"
        end
    end

    def show
        @objetivo = Objetivo.find(params[:id])
    end

    def edit
        @objetivo = Objetivo.find(params[:id])
    end

    def update
        @objetivo = Objetivo.find(params[:id])
        if @objetivo.update(objetivo_params)
            flash[:success] = "Objetivo atualizado"
            redirect_to dashboards_path
        else
            render 'edit'
        end
    end

    private
    def objetivo_params
        params.require(:objetivo).permit(:titulo, :descricao)
    end
end

app/helpers/objetivos_helper.rb
module ObjetivosHelper
end

app/views/objetivos/edit.html.erb
<section class='main-content'>
  
  <div class='form-titulo'>Cadastrar objetivo</div>

  <div class='white-box'>
    <% if @objetivo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@objetivo.errors.count, "erro") %> impedem que o objetivo seja gravado no banco de dados:</h2>
    
        <ul>
        <% @objetivo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for(@objetivo) do |form| %>
      <p class='form-label'><%= form.label :titulo %></p>
      <p class='form-input'><%= form.text_field :titulo %></p>
    
      <p class='form-label'><%= form.label :descricao %></p>
      <p class='form-input'><%= form.text_field :descricao %></p>

      <p class='form-btn'><%= form.submit 'Adicionar Objetivo' %></p>
    <% end %>
  </div>

</section>

app/views/objetivos/new.html.erb
<section class='main-content'>
  
  <div class='form-titulo'>Cadastrar objetivo</div>

  <div class='white-box'>
    <% if @objetivo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@objetivo.errors.count, "erro") %> impedem que o objetivo seja gravado no banco de dados:</h2>
    
        <ul>
        <% @objetivo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with scope: :objetivo, url: objetivos_url, local: true do |form| %>
      <p class='form-label'><%= form.label :titulo %></p>
      <p class='form-input'><%= form.text_field :titulo %></p>
    
      <p class='form-label'><%= form.label :descricao %></p>
      <p class='form-input'><%= form.text_field :descricao %></p>

      <p class='form-btn'><%= form.submit 'Adicionar Objetivo' %></p>
    <% end %>
  </div>

</section>

app/views/objetivos/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @objetivo.titulo %>
</p>
 
<p>
  <strong>Descrição:</strong>
  <%= @objetivo.descricao %>
</p>