config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "dashboards", to: "dashboards#show"
  
  get 'sessions/new'

  get 'usuarios/new'
    
  get 'objetivos', to: 'objetivos#new'
  get 'objetivos/:id/edit', to: 'objetivos#edit', as: 'edit_objetivo'
  resources :objetivos

  get 'dividas', to: 'dividas#new'
  resources :dividas

  get 'rendas', to: 'rendas#new'
  resources :rendas

  get 'recursos', to: 'recursos#new'
  resources :recursos

  get 'usuario_info', to: 'usuario_info#new'
  get 'usuario_info/:id/edit', to: 'usuario_info#edit', as: 'edit_usuario_info'
  resources :usuario_info

  resources :usuarios
  get 'sign_in' => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  root 'sessions#new'

end

app/views/layouts/_footer.html.erb
<footer>
    <h3><strong>Engenharia de Sistemas de Informação - Grupo 1</strong></h3>
    <p>Rhuan Carlos dos Santos Ferreira - 10259071</p>
    <p>Ivo de Andrade de Deus - 80752380</p>
    <p>Gustavo Nascimento da Cunha - 10438400</p>
    <p>Gustavo Ferreira Silva - 10687767</p>
    <p>Renan Gonçalves Mastropaolo - 10892593</p>
    <p>Ian Lourenço Bezerra da Silva - 10430937</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class='header-logo'>
    <%= image_tag 'logo.svg', style: '' %>
    <p>MoneyConteiner</p>
  </div>

  <div>
    <nav class='header-nav'>
      <ul>
        <% if logged_in? %>
          <li class='header-btn'><%= link_to "Usuários", usuarios_path %></li>
          <li class='header-btn'><%= link_to "Página Principal", dashboards_path %></li>
          <li class='header-btn'><%= link_to "Configurações", edit_usuario_path(current_usuario) %></li>
          <li class='header-btn'><%= button_to "Sair", sign_out_path, method: "delete" %></li>
        <% else %>
          <li class='header-btn'><%= link_to "Log in", root_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EPEngsi2022</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>